version: '3.8'

services:
  web:
    build: 
      context: athlos_hotel_api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: athlos_hotel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  puppeteer:
    build:
      context: puppeteer
      dockerfile: ./Dockerfile
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

volumes:
  postgres_data:
